name: Lulu.B
favicon: null
layout_spectrum: 0.56579
typography_spectrum: 0.28698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffbe5'
    - '#8ae7df'
    - '#fee0d4'
    - '#4bdfde'
    - '#d2f2e3'
  brandStrength: 0.75
  lightness: 0.688027
  saturation: 0.4831366
  rhythmicContrast: 0.3195615
purpose: []
