layout_spectrum: 0.9569983
typography_spectrum: 0.4342327
color:
  lightness: 0.688027
  brandStrength: 0.6315346
  saturation: 0.4831366
  rhythmicContrast: 0.3195615
  brandColors:
    - '#413030'
    - '#0288C6'
    - '#FBF9FB'
    - '#DFB588'
    - '#6EACD0'
name: Lulu.B
